/** Common CSS optional subjects for qualifier profiles. */
export const CSS_OPTIONAL_SUBJECTS = [
  "Accountancy & Auditing",
  "Agriculture & Forestry",
  "Anthropology",
  "Applied Mathematics",
  "Arabic",
  "Botany",
  "British History",
  "Business Administration",
  "Chemistry",
  "Computer Science",
  "Constitutional Law",
  "Criminology",
  "Economics",
  "English Literature",
  "Environmental Sciences",
  "Gender Studies",
  "Geography",
  "Geology",
  "Governance & Public Policies",
  "History of Pakistan & India",
  "History of USA",
  "International Law",
  "International Relations",
  "Islamic History & Culture",
  "Islamic Studies",
  "Journalism & Mass Communication",
  "Law",
  "Mercantile Law",
  "Muslim Law & Jurisprudence",
  "Pashto",
  "Persian",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Punjabi",
  "Pure Mathematics",
  "Sindhi",
  "Sociology",
  "Statistics",
  "Town Planning & Urban Management",
  "Urdu Literature",
  "Zoology",
];
